### ISSUE TITLE
can u share the database too pls 

### ISSUE THREAD

**Issue by shook1337** [bmarkovic17/contacts#1]
i need this project

**Comment by bmarkovic17** [comment]
Unfortunately I don't have a database with data.
Upon application start EF will create an empty PostgreSQL database for you which you can populate with mock data if you want. You can find some mock data in the migrations.

Let me know if I can help you in any way.

**Comment by shook1337** [comment]
if the project can run with only database i can create a contact in swagger if possible where can i message you to help me

**Comment by bmarkovic17** [comment]
You can contact me on my email: bmarkovic17@outlook.com
